# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../src/GLideNUI/FullscreenResolutions.h \
    ../../src/GLideNUI/GLideNUI.h \
    ../../src/GLideNUI/Settings.h \
    ../../src/GLideNUI/AboutDialog.h \
    ../../src/GLideNUI/ConfigDialog.h
SOURCES += ../../src/GLideNUI/AboutDialog.cpp \
    ../../src/GLideNUI/ConfigDialog.cpp \
    ../../src/GLideNUI/QtKeyToHID.cpp \
    ../../src/GLideNUI/FullscreenResolutions_windows.cpp \
    ../../src/GLideNUI/GLideNUI.cpp \
    ../../src/GLideNUI/ScreenShot.cpp \
    ../../src/GLideNUI/Settings.cpp
FORMS += ../../src/GLideNUI/AboutDialog.ui \
    ../../src/GLideNUI/configDialog.ui
RESOURCES += ../../src/GLideNUI/icon.qrc
