# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = GLideNUI
DESTDIR = ./bin/Win32/Release/lib
CONFIG += staticlib release
DEFINES += QT_STATICPLUGIN OS_WINDOWS
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(GLideNUI.pri)
